### PR TITLE
Fix emscripten & OS/X

### PR DESCRIPTION
**Pull request by MisterTea**

### CODE REVIEW

**Comment by mmatyas** [comment]
Thanks! Does this mean that you've managed to build and play the emscripten port, without compile or runtime errors? I'm having some troubles building it currently, so I couldn't test your patch in browsers yet.
I've tried a native Linux+SDL1.2 build though, but the game got stuck in a forever loop, freezing the PC... I plan to rewrite/work on the GFX code and fix emscripten after the network part gets finished, so if you don't mind maybe we should put this patch off until then.
There are no problems with the `Fix OSX` commit though, if you send a separate pull request, I can merge it.

**Comment by MisterTea** [comment]
Hey. You need to replace the pngs with the ones from my data.zip for it to
work. OS/X and emscripten only support 32-bit pngs so I converted them all

**Comment by mmatyas** [comment]
Yes, I did that, and the game still freezed. But I think I can check it on other devices next week too, to make sure.

"OS/X only support 32-bit pngs": Could you explain that? I'm not using OS/X, but as far as I know the original SMW worked with the same graphics that are used currently. Are there display issues or something?

**Comment by MisterTea** [comment]
Sure, here's what's going on:

The function "ValidSkinSurface" was returning false on OS/X because BitsPerPixel was 32, not 24.  Although the PNG was 24 bits-per-pixel, the OS/X backend for SDL_Image was adding an alpha channel because OS/X doesn't support pngs without an alpha channel.  Same for emscripten.  I addressed this by adding an alpha channel to the pngs and then checking for 32-bit pngs instead of 24-bit.  I also changed the skin generation code to expect an alpha channel and skip over it when building the skins.

If any part of making a skin fails, the code is an infinite loop because of this:
```
                    //Skip skins that are invalid
                    while (!rm->LoadMenuSkin(iPlayerID, game_values.skinids[iPlayerID], iNewTeam, false)) {
                        if (++game_values.skinids[iPlayerID] >= skinlist->GetCount())
                            game_values.skinids[iPlayerID] = 0;
                    }
```

None of the skins are valid so it loops forever.

I haven't tried linux, but I'll take a look today and figure out what's wrong.

**Comment by MisterTea** [comment]
Hmm, actually I think this is a bug in SDL1, or at least my version of it..  When I switch to SDL2, it works fine with 24-bit pngs.  I'm going to close this PR and submit a new one for the OS/X fix commit.

**Pull request closed without merging**
