### PR TITLE
Do not play starman theme if music is muted.

### LINKED ISSUE #161: Starman theme counts as sfx instead of music for volume sliders
If I've set the music volume to 0 because I'm playing my own music, that should also prevent the starman theme from playing

### PR DESCRIPTION
**Pull request by AzureBerylBlue**
Fixes #161 
The starman theme is currently part of sound packs instead of music packs, so it technically counts as sfx, so this isn't a proper fix, but it does work.

### CODE REVIEW

**Comment by mmatyas** [comment]
I'm fine with the workaround, but what I was wondering is whether this is something to change in the first place? Yes, the starman theme is longer than most effects, but it's still something related to an in-game event, with a limited length, and it gives audio cues about the game situation. So it's not like a continuous, looping background music. What do you think? @AzureBerylBlue @ncrecc

**Comment by ncrecc** [comment]
I think the player with starman flashing colors rapidly is a good enough visual cue that ignoring the audio cue doesn't change much.

**Comment by AzureBerylBlue** [comment]
Well, the starman theme already stops the background music from playing while it plays, so it really should have counted as music in the first place.

**Comment by mmatyas** [comment]
Hm I guess that's also a valid argument.

**Pull request merged**
