### PR TITLE
Improved .gitignore

### PR DESCRIPTION
**Pull request by Pheazant**
smw creates a lot of files when building.

### CODE REVIEW

**Comment by mmatyas** [comment]
Hi, the build files CMake creates depend on your OS, compiler, build tools, target platform, as well as the build targets themselves. It is not really feasible to maintain a list of all possible combinations; instead, the recommended way is to build in a directory separate from the source files.

**Comment by Pheazant** [comment]
I see. Why not try to cover as much as we can, though? Cleaning and rebuilding every time one would like to see a diff can be a point of friction - even covering a few critical paths might make dev easier for people.

**Comment by mmatyas** [comment]
Separating the source code from the build directory is the recommended way to build the project, and this is also what our README says in the build section. Rather than covering and continuously maintaining the possible combinations by ourselves, in my opinion we should instead direct our developers to the preferred usage of the tools, which would also possibly help them on other projects.

In this particular case, you can use `git clean` to remove all non-source files, and you can always re-run CMake to build the project in a new directory.

**Comment by Pheazant** [comment]
Sounds good.

**Pull request closed without merging**
