### PR TITLE
Remove savepng from SDL2 builds

### PR DESCRIPTION
**Pull request by AzureBerylBlue**

### CODE REVIEW

**Comment by mmatyas** [comment]
Why?

**Comment by AzureBerylBlue** [comment]
I tried compiling on Windows with both the SDL2 flag and PNG flag on and got errors, and this fixed it.

**Comment by mmatyas** [comment]
Hm it seems we don't even have this file anymore; you can remove the whole block.

**Comment by AzureBerylBlue** [comment]
Are you sure? It's right here:
https://github.com/mmatyas/supermariowar/blob/master/src/common/savepng.h
And it's still included in SDL1 builds.
https://github.com/mmatyas/supermariowar/blob/master/src/screenshot/screenshot.cpp#L20

**Comment by mmatyas** [comment]
Ah looks like things were moved around, in this case it should be

`list(APPEND COMMON_SRCS savepng.cpp)`

I wonder if that fixes the build too.

**Comment by AzureBerylBlue** [comment]
Ok, I updated it.

**Pull request merged**
