### PR TITLE
Fix AI not jumping when they should

### PR DESCRIPTION
**Pull request by AzureBerylBlue**
This code was only being called every 4 frames, so it would break if the AI landed on the ground before the code executed.

### CODE REVIEW

**Comment by mmatyas** [comment]
What are the effects of this patch, ie. does the AI now jumps more often? What was exactly broken before?

The code itself works fine, there's just a small warning: 
image

**Comment by AzureBerylBlue** [comment]
The problem was that if that code did not execute, the AI could end up in a state where they can't jump at all until it walks off whatever platform it's standing on, or until it stops trying to jump, which rarely happens. After looking at the code more, I think the AI was trying to jump way too often, so I made the following changes:
- Allowed the AI to down jump through solidtops by just pressing down, just like keyboard players. Otherwise, the code would make them jump up if they couldn't down jump.
- Removed the rng based jumping, replaced it with code that makes them jump only if they get stuck.
- Removed jumping when the target is significantly below.
- I also added a *moveToward = true for the case where the AI is far below in the opposite corner of the map, so it won't just stand there doing nothing.

**Comment by mmatyas** [comment]
Nice, tested the changes and seems to be working fine. Do you plan some more changes or is this ready?

**Comment by AzureBerylBlue** [comment]
It's ready, unless you think there is something else I should add.

**Pull request merged**
