### PR TITLE
Fix broken world graphics

### LINKED ISSUE #83: World graphics are broken
world
It looks like it is using world_foreground.png instead of world_foreground_special.png
This image is from 1.8 beta 2:
world2

### PR DESCRIPTION
**Pull request by AzureBerylBlue**
Fixes #83

### CODE REVIEW

**Comment by mmatyas** [comment]
I'm still not sure whether the graphics change was intentional or not :/ I wonder which commit introduced it in the first place.

**Comment by AzureBerylBlue** [comment]
Compare the 1.8 beta 2 world.cpp with the latest world.cpp.

**Comment by AzureBerylBlue** [comment]
Here is the bad commit: edfed908ac3c33f35963442b408c1818dec20c80

**Comment by mmatyas** [comment]
Thanks! It does look like a bug. Could you clean up this branch to only contain the "Fix broken world graphics" commit? I'm happy to merge it then.

**Pull request closed without merging**
